version: "3"

services:
  db_pg:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
#      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
#       - pg_data:/var/lib/postgresql/data/
      - ./docker/postgres/init.slq:/docker-entrypoint-initdb.d/init.slq
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db_pg
    ports:
    - "8000:8000"

#volumes:
#  pg_data:
# /usr/local/bin/docker-compose build --no-cache
# /usr/local/bin/docker-compose up